# SPDX-License-Identifier: GPL-2.0-only

# Copyright (C) 2025-2026 landerrosette

obj-m += xt_strider.o
ccflags-y += -I$(STRIDER_ABS_TOP_SRCDIR)/include
KBUILD_EXTRA_SYMBOLS += $(STRIDER_ABS_TOP_SRCDIR)/strider/Module.symvers
