# SPDX-License-Identifier: GPL-2.0-only

# Copyright (C) 2025-2026 landerrosette <57791410+landerrosette@users.noreply.github.com>

obj-m += strider.o
strider-y := main.o netlink.o core.o ac.o
ccflags-y += -I$(STRIDER_ABS_TOP_SRCDIR)/include

obj-$(CONFIG_STRIDER_AC_KUNIT_TEST) += strider_ac_test.o
strider_ac_test-y := ac_test.o ac.o
