#ifndef STRIDER_PROTOCOL_H
#define STRIDER_PROTOCOL_H


#define STRIDER_GENL_FAMILY_NAME "strider"
#define STRIDER_GENL_VERSION 1

enum strider_genl_commands {
    STRIDER_CMD_UNSPEC,
    STRIDER_CMD_ADD_RULE,
    STRIDER_CMD_DEL_RULE,
    __STRIDER_CMD_MAX,
};

#define STRIDER_CMD_MAX (__STRIDER_CMD_MAX - 1)

enum strider_genl_attrs {
    STRIDER_NLA_UNSPEC,
    STRIDER_NLA_KEYWORD,
    STRIDER_NLA_ACTION,
    __STRIDER_NLA_MAX,
};

#define STRIDER_NLA_MAX (__STRIDER_NLA_MAX - 1)


#endif //STRIDER_PROTOCOL_H
