obj-m := strider.o
strider-y := strider_manager.o strider_ac.o
ccflags-y += -I$(src)/../include

obj-$(CONFIG_STRIDER_AC_TEST) := strider_ac_test_kunit.o
strider_ac_test_kunit-y := strider_ac_test.o strider_ac.o
